### ISSUE TITLE
.NET Version Not Working Reliably

### ISSUE THREAD

**Issue by AlexVPerl** [MobilityData/gtfs-realtime-bindings#29] opened 2017-11-22 07:58 UTC
Having an issue with the .NET version. 

It does not seem to populate TripUpdate consistently. Seems when Vehicle is available TripUpdate is not populated.

Tested the same feed using JAVA code from OneBusAway and TripUpdate is there on every entity item.

What could be the reason? Any ways to get TripUpdate to populate reliably ?

**Comment by barbeau** [comment] 2019-03-01 10:38
@AlexVPerl Could you please provide the GTFS-realtime feed that you are using?

**Comment by barbeau** [comment] 2019-04-30 21:59
So I believe this is actually a duplicate of https://github.com/MobilityData/gtfs-realtime-bindings/issues/32, so I'm closing it as a duplicate.

**Closed by barbeau** 2019-04-30 21:59 UTC
Labels: bug, duplicate
